# Conclusiones
Aunque la agricultura de la UE solo representa en torno al 1% de su PIB, sigue siendo un sector importante. El 40% del territorio de la UE está dedicado a la agricultura, lo que tiene implicaciones medioambientales y en la gestión del territorio. 

Al analizar los países miembros de la UE, se observa como los países de centro Europa y Europa del sur-oeste debido a su clima, relieve y extensión obtienen una mayor producción agrícola, donde destaca Francia con una producción superior a los 51 illones de euros e Italaia, España y Alemania con una producción de entorno a los 37 millones de euros. Sin embargo, los estados con mayor peso en la agricultura en el PIB nacional, no se corresponden con aquellos que más producen sino con aquellos que presentan unas econonías menos desarolladas, donde destacan: Rumanía, Bulgaria y, sobre todo, Grecia.

En relación a los cultivos específicos, la UE destaca en la producción de cultivos herbáceos: cultivos de raíz y, especialmente cereales, los cuales suponen más del 40 % de la producción. Alternativamente, tras analizar los países de forma individual, se aprecia como aquellos con mayor superficie de centro-Europa y el sur-este de Europa concentran la mayor parte de la producción. Además, se distingue una dualidad en el modelo agrícola de la UE, donde los países del centro destacan por sus cultivos extensivos mientras que los del mediterráneo destacan por un el cultivo intensivo basado en el regadío.

En este contexto, la PAC es una política que tiene como objetivo integrar la agricultura en la sociedad. Para ello se otorgan subvenciones a través de distintos fondos. Las ayudas se asignan en función del tipo de cultivo y su rendimiento, entre otros factores. En el caso de España, las ayudas suponen el 20% de los ingresos agrarios.

Paralelamente, en relación a la balanza comercial, la UE importa principalmente aquellos cultivos con baja producción  como el caso de las semillas oleaginosas y por el contrario exporta aquellos en los que está altamente especializada como el vino o el aceite de oliva. 


Finalmente, al comparar la UE con otras potencias mundiales como China o EE. UU., percibimos si bien sus métodos son diferentes, las tres potencias centran sus cultivos en los cereales, y por otro lado, aunque la UE no dedica tanto porcentaje del PIB en este sector como China, es el mayor exportador y menor importador de estas tres potencias.